### ISSUE TITLE
issues in views not displayed after Sublime 3 update

### ISSUE THREAD

**Issue by born4new** [pderichs/sublime_rubocop#27]
I'm running Sublime text 3 (build 3083) on OS X 10.10.2.

After the upgrade of Sublime text 3, I don't see the rubocop violations in Sublime. If i launch the sublime_rubocop in the terminal, it works great. They're just not displayed in the view...

Is it because of the latest version of sublime text 3?

**Comment by ecnalyr** [comment]
+1, I also get occasional crashes due to the plugin (I don't have the error message handy, but when I removed rubocop I stopped experiencing crashes).  This only started after the latest Sublime Text 3 update.

**Comment by pderichs** [comment]
@born4new Hm, strange. I am also using the latest version on Mac OS and it works fine for me. 

@ecnalyr  I never saw any crashes caused by the plugin until now, but I will keep an eye on it.

I changed the calls to rubocop in the plugin a few minutes ago - I am not sure if that fixes your problem, but can you both update the plugin and test again? At least we could then confirm the problem is also present in the current version :blush: . Thank you.

**Comment by ecnalyr** [comment]
Updated, will keep an eye on it.  Thanks!

**Comment by born4new** [comment]
Hi @pderichs,

I see in the console that rubocop is correctly executed, but I don't see the red indicators in Sublime. Here are my current tools' versions:

ruby 2.2.2
rubocop 0.30.1
sublime text 3, build 3083

I'm at the latest version of sublime_rubocop.

Cheers,

David D.

**Comment by pderichs** [comment]
@born4new Can you share your default and user config of the plugin? Is the `mark_issues_in_view` setting in the sublime rubocop config set to true? 

Are there any errors in the Sublime Text console?

**Comment by born4new** [comment]
Hi @pderichs,

I'll look into that next week, I'll keep you posted.

Thanks!

**Comment by born4new** [comment]
Hi there,

I tried from scratch, and it's working fine again. thanks a lot!

**Comment by pderichs** [comment]
Glad to hear the problem is solved. Cheers!
